### ISSUE TITLE
Interaction code of final state particles

### ISSUE THREAD

**Issue by njbruhwiler** [cepgen/cepgen#53]
Hi Laurent, 

When running CepGen with the 'pptoff' process, the final-state particles have interaction codes of 2 (decay) instead of 1 (stable final state). This is not an issue with 'lpair' mode. Config files, log files, and output hepmc files are included below. Do you have any advice about this? Thanks!

Config: [https://github.com/njbruhwiler/yy-gen-playground/blob/cepgen-test/configs/cepgen-yyll-ds.py](url)
Log file: [https://github.com/njbruhwiler/yy-gen-playground/blob/cepgen-test/logs/cepgen_yyll_ds.log](url)
Output hepmc: [https://github.com/njbruhwiler/yy-gen-playground/blob/cepgen-test/hepmc_files/cepgen_yyll_ds.hepmc](url)

@spagangriso
@adimitrievska
@angirar

**Comment by forthommel** [comment]
Hi @njbruhwiler,

Many thanks for reporting this (and #52)! #54 should address this.
In particular for this status code, it is true that the particles produced should be considered as final state, unless specified differently (e.g. two-photon production of quark pairs).
A follow-up sanitisation work can also be done on hadronisation/event treatment algorithms to make sure a proper status code of particles is fed.

Thanks again!
Laurent
