### ISSUE TITLE
In-el vs. el-in modes

### ISSUE THREAD

**Issue by njbruhwiler** [cepgen/cepgen#57]
Hi Laurent,

Thanks for responding to the last issues, they were fixed by v1.2.1! Something else I noticed is that for lpair mode, the in-el and el-in processes now have the same cross section but it seems like the same proton is dissociating for both:
<img width="333" alt="lpair_leading_lepton_eta" src="https://github.com/cepgen/cepgen/assets/51885369/d826f31f-0664-42d9-8a99-da2b1cba0d2e"><img width="333" alt="lpair_sub_lepton_eta" src="https://github.com/cepgen/cepgen/assets/51885369/f29875d3-97f0-4091-a08a-5c528c4dde0d">

Configs used to make these plots:
ds: [https://github.com/njbruhwiler/yy-gen-playground/blob/cepgen-test/configs/cepgen-lpair-yyll-ds.py](url)
sd: [https://github.com/njbruhwiler/yy-gen-playground/blob/cepgen-test/configs/cepgen-lpair-yyll-sd.py](url)

This isn't a problem with the pptoff mode:
<img width="333" alt="yyll_leading_lepton_eta" src="https://github.com/cepgen/cepgen/assets/51885369/a0d0dc1c-c5a8-470a-9ff7-cc6460f258a2"><img width="333" alt="yyll_sub_lepton_eta" src="https://github.com/cepgen/cepgen/assets/51885369/a50d45c7-859b-43e2-a307-7920235ce9f8">

Configs used to make these plots:
ds: [https://github.com/njbruhwiler/yy-gen-playground/blob/cepgen-test/configs/cepgen-yyll-ds.py](url)
sd: [https://github.com/njbruhwiler/yy-gen-playground/blob/cepgen-test/configs/cepgen-yyll-sd.py](url)

Have you noticed this? Thanks for your help!
-Natalie
@spagangriso
@adimitrievska
@angirar

**Comment by forthommel** [comment]
Hi Natalie!

And many thanks for reporting this symmetry issue. Indeed although the inelastic-elastic and elastic-inelastic modes were properly symmetrised, leading to a proper momentum balance, their z-axis remained unchanged.

A fix was just merged into the master branch. Could you please have a look and confirm the good behaviour now?

Many thanks in advance!

Kind regards, Laurent
